title: "GitHub Actions: Writing Docker Actions"
tagline: Create custom automation tasks for your unique workflow using GitHub Actions
description: >-
  Learn how to write your own GitHub Docker Action!  This course will
  empower you to begin automating customized tasks unique to your workflow.
template:
  repo: "write-docker-actions-template"
  name: "write-docker-actions"
before:
  - type: updateBranchProtection
  - type: createLabel
    name: first-cat-fact
    color: FFBD33
  - type: createLabel
    name: second-cat-fact
    color: 33FFBD
  - type: createLabel
    name: third-cat-fact
    color: 3F8A99
  - type: createIssue
    title: Start here!
    body: 01_welcome-issue.md
    action_id: welcomeIssue
  - type: respond
    issue: "%actions.welcomeIssue.data.number%"
    with: 01_welcome-activity.md
    data:
      quicklink: "%payload.repository.html_url%/new/master?filename=.github/workflows/my-workflow.yml&workflow_template=blank"
      actionsUrl: "%payload.repository.html_url%/actions/new"
steps:
  - title: Setup a workflow file
    description: Create a pull request to add a workflow
    event: pull_request
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create my-workflow.yml'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Create my-workflow.yml

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Create my-workflow.yml
          # if those gates === true Then do this stuff
      - type: closeIssue
        issue: Start here!
      - type: respond
        with: 01_explain-workflow.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 01_explain-environment.md
      - type: respond
        with: 01_explain-syntax.md
      - type: respond
        with: 02_modify-workflow.md
        issue: Create my-workflow.yml
        data:
          workflowFile: "%payload.repository.html_url%/edit/%payload.pull_request.head.ref%/.github/workflows/my-workflow.yml"

  # - title: Run a workflow
  #   description: Wait for GitHub to run the workflow and report back the results
  #   event: check_suite.completed
  #   link: "{{ repoUrl }}/pull/2"
  #   actions:
  #     - type: gate
  #       left: "%payload.check_suite.app.name%"
  #       operator: ===
  #       right: "GitHub Actions"
  #       else:
  #         - type: respond
  #           issue: Initial workflow
  #           with: debug.md
  #           data:
  #             debug: "%payload%"
  #     - type: respond
  #       with: 02_workflow-results.md
  #       issue: Create my-workflow.yml
  #       data:
  #         actionsUrl: "%payload.repository.html_url%/actions"
  #     - type: getPullRequest
  #       pullRequest: Create my-workflow.yml
  #       action_id: iwPr
  #     - type: respond
  #       with: 02_modify-workflow.md
  #       issue: Create my-workflow.yml
  #       data:
  #         workflowFile: "%payload.repository.html_url%/edit/%actions.iwPr.data.head.ref%/.github/workflows/my-workflow.yml"

  - title: Add an Action reference
    description: Add an Action reference to the workflow file
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: getPullRequest
        pullRequest: Create my-workflow.yml
        action_id: workflowPr
      - type: respond
        with: 03_reference-actions.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.workflowPr.data.head.ref%/.github/workflows/my-workflow.yml"

  - title: Creating the Action metadata
    description: Create an action.yml file and add necessary metatdata for our Action
    event: pull_request.synchronize
    actions:
      - type: createIssue
        title: Your first Docker action
        body: docker-overview.md
        action_id: dockerOverview
      - type: createReview
        event: APPROVE
        body: 04_on-to-actions.md
        data:
          issueUrl: "%actions.dockerOverview.data.html_url%"
        pullRequest: Create my-workflow.yml
      - type: mergePullRequest
      - type: respond
        with: 05_explain-actions.md
        issue: Your first Docker action
      - type: respond
        with: 05_explain-metadata.md
        issue: Your first Docker action
      - type: respond
        with: 05_create-metadata.md
        issue: Your first Docker action
        data:
          quicklink: "%payload.repository.html_url%/new/master?filename=.github/actions/hello-world/action.yml"

  - title: Creating the action logic
    description: Adding source code to the action
    event: pull_request
    # link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create my-workflow.yml'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Create action.yml

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Create my-workflow.yml
          # if those gates === true Then do this stuff
      - type: respond
        with: 06_hello-docker-actions.md
        action_id: helloPr
        data:
          quicklink: "%payload.repository.html_url%/new/hello-world?filename=.github/actions/hello-world/main.go"
          # actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 05_hello-pr.md
        issue: Your first Docker action
        data:
          pullUrl: "%actions.helloPr.data.html_url%"
      - type: closeIssue
        issue: Your first Docker action

  - title: Create the action Dockerfile
    description: Creat a Dockerfile containing the actions source code
    event: pull_request.synchronize
    actions:
      ####################################
      #### Testing gates #################
      ####################################

      # get tree
      - type: getTree
        action_id: isInTree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      # check for a file in a tree
      - type: gate
        left: "%actions.isInTree.data.tree%"
        operator: includes
        right: path:hello-world/main.go
        else:
          # if file isn't where expected find true location
          - type: findInTree
            path: main.go
            multiple: true
            action_id: fileLocation
          # help user with proper file location
          - type: respond
            with: e-no-file.md
            data:
              haveFile: "%actions.fileLocation%"
              needFile: ".github/actions/hello-world.go"

      - type: getFileContents
        filename: ".github/actions/hello-world/main.go"
        action_id: mainGoContents
      - type: gate
        left: "%actions.mainGoContents%"
        else:
          - type: respond
            with: e-404.md
            data:
              need: ".github/actions/hello-world/main.go"
      - type: gate
        left: "%actions.mainGoContents%"
        operator: ===
        right: |-
          package main

          import "fmt"

          func main() {
          fmt.Println("Hello Docker Actions")
          }
        else:
          - type: respond
            with: wrong-content.md
            data:
              filename: ".github/actions/hello-world/main.go"
              correctContent: |-
                package main

                import "fmt"

                func main() {
                fmt.Println("Hello Docker Actions")
                }
      # - type: respond
      #   with: filecontents.md
      #   data:
      #     contents: "%actions.mainGoContents%"
      - type: respond
        with: 07_create-dockerfile.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Adding input parameters to metadata
    description: extend your action to accept input parameters
    event: pull_request.synchronize
    actions:
      - type: respond
        with: 07_hello-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

      - type: respond
        with: 07_add-input-params.md
      - type: respond
        with: 07_update-metadata.md

  - title: Adding input parameters to source code files
    description: extend your action to accept input parameters
    event: pull_request.synchronize
    actions:
      - type: respond
        with: 07_update-source-code.md

  - title: Using input parameters in the workflow
    description: Assign values to the newly created input parameters
    event: pull_request.synchronize
    actions:
      - type: respond
        with: 07_update-workflow.md

  - title: Exploring your input parameters
    description: view the results of adding input parameter
    event: pull_request.synchronize #ideally would like workflow complete to trigger this
    actions:
      - type: respond
        with: 08_input-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: removeBranchProtection
      - type: respond
        with: 08_experiment.md

  - title: Integrating Actions with external APIs
    description: Write a new Action that call an external API
    event: pull_request.closed
    actions:
      - type: updateBranchProtection
      - type: createIssue
        body: 09_external-apis.md
        title: Kittens everywhere
        action_id: catFact
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 08_next-steps.md
        issue: Hello Action
        data:
          issueUrl: "%actions.catFact.data.html_url%"
      - type: respond
        with: 09_new-action.md
        issue: Kittens everywhere
        data:
          # The following workflowFile var does not point where it should for some reason
          workflowFile: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Create your new Action metadata
    description: Comment out the lines in the workflow to prevent unwanted runs
    event: pull_request
    # link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create my-workflow.yml'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: External APIs
          # if those gates === true Then do this stuff
      - type: closeIssue
        issue: Kittens everywhere
      - type: respond
        with: 10_create-metadata.md

  - title: Create your action's source code files
    description: Add main.py to your Action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-python-file.md

  - title: Add Python dependencies
    description: Add the requirements.txt file
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-requirements.md

  - title: Create the Dockerfile for the action
    description: Add the Dockerfile to the action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-dockerfile.md

  - title: Use the cat fact action in a workflow
    description: Edit the workflow file to now use the newly created cat fact action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: getPullRequest
        pullRequest: External APIs
        action_id: apiPr
      - type: respond
        with: 11_edit-workflow.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.apiPr.data.head.ref%/.github/workflows/my-workflow.yml"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Having actions teach us about cats
    description: Trigger your workflow to get cat facts
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: removeBranchProtection
      - type: respond
        with: 12_trigger-workflow.md
        issue: External APIs
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Configure the workflow for a third Action
    description: Edit the workflow to accomodate the third action
    event: pull_request.closed
    actions:
      - type: updateBranchProtection
      - type: createIssue
        body: 13_action-three-workflow.md
        title: Consuming Action Outputs
        action_id: outputIssue
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
          workflowFile: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
      - type: respond
        with: 12_next-steps.md
        issue: External APIs
        data:
          issueUrl: "%actions.outputIssue.data.html_url%"

  - title: Write the final Action
    description: Create an Action that consumes output from another Action and uses the JavaScript actions toolkit
    event: pull_request
    # link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create my-workflow.yml'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Use Outputs
          # if those gates === true Then do this stuff
      - type: closeIssue
        issue: Consuming Action Outputs
      - type: respond
        with: 14_action-three.md

  - title: Add third Actions metadata
    description: Create the metadata for the third Action
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: respond
        with: 14_create-metadata.md

  - title: Add third Actions JavaScript files
    description: Create the JavaScript files for the third Action
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: respond
        with: 14_create-js-files.md

  - title: Create the final actions Dockerfile
    description: Add a pull request label to trigger the workflow
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: respond
        with: 14_create-dockerfile.md

  - title: Trigger the third Action
    description: Add a pull request label to trigger the workflow
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: removeBranchProtection
      - type: respond
        with: 15_add-a-label.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Wrapping things up
    description: Final notes before you go
    event: pull_request.closed
    actions:
      - type: createIssue
        title: Last minute notes
        body: great-job.md
      - type: respond
        issue: Last minute notes
        with: 16_publishing.md
      - type: respond
        issue: Last minute notes
        with: 16_complete.md
